### ISSUE TITLE
Using wrong Contacts on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by Revisor01** [libasys/contactsplus#103]
On my OS X 10.11 El Capitan the contacts app fetching the wrong contacts from owncloud. The settings are all correct. I copied the URL for OS X out of contacts+. On my iPhone and iPad it is working. When I deactivate the "standard" contacts app in owncloud it doesn't get any contacts.
##

**Comment by ghost** [comment]
Hi,

@Revisor01 
very likely an issue with the .well-known URLs at your setup which redirects to /remote.php/cardav instead of /remote.php/contactsplus

Ref: https://github.com/owncloud/core/issues/20012

I think there is nothing what can be fix in the app itself.

_Edit_

You can test your redirect by calling the .well-known URL like:

```
curl -i https://example.com/.well-known
```

this probably redirects like described above.

_Edit2_

Ref for an issue at the contacts app: https://github.com/owncloud/contacts/issues/1058
