### ISSUE TITLE
Contact name duplicated when no company name present

### ISSUE THREAD

**Issue by jancborchardt** [libasys/contactsplus#22]
When there is no company name set for a contact (most cases), the name is duplicated there. This is completely unnecessary.

**Comment by deMattin** [comment]
No not completely.
I think, @libasys did here something very special.
Business contacts (contacts with a company entry) are sorted by surname and for private contacts without a filled in company the fullname is the (virtual) company and so they are sorted by first name.

This is a real intelligent feature - much better than "normal" sorting by company or by first name or by last name.
Because you search your friends normally by firstname and businesss contacts more by surname - often you don't even remember their firstname.
As I once have recognized this sorting feature, I liked it very much and hope, this is really a feature and not a bug ... ;)

But may be it should be possible to overwrite this "intelligent" sorting by a simple surname/firstname/company sorting.
I think, this overwriting is in development in the pulldown box "company/name/adress/mail" where I see no function by now and where a firstname/surname sorting would also be missing.

**Edit:**
Sorry, I have to readjust my opinion.
If you import a contact in contactsplus, it is sorted by firstname and if you edit (only open and save) it, it is sorted by surname.
Not an intelligent feature - just an importing bug ... :/

**Comment by libasys** [comment]
New behaviour:
if lastname and no orga then fullname = lastname
if lastname and orga then fullname = orga
if orga and no lastname then fullname = orga

**Comment by deMattin** [comment]
It's ok like it is in actual master, I think.
But additional sorting should be possible (#31)
And this pulldown menu (Organisation, Name, Adresse, E-Mail) is a filter for searching.
(Now) it works well and case insensitive as it should do.

**Comment by jancborchardt** [comment]
@libasys so the closing means what? It’s solved, or you don’t care? A clarifying comment, ideally with reference to the commit with the change would be good.
