### ISSUE TITLE
1.0.2 - Is the sorting selection editable?

### ISSUE THREAD

**Issue by MNOCFan** [libasys/contactsplus#34]
In the Contacts+ app, is the "sort by" drop down selection editable? For example, can I add "Department" to be sorted by? Thanks.

**Comment by libasys** [comment]
this is not a sort field in early version this was a searching feature, but with current version this dropdown is removed!

**Comment by deMattin** [comment]
This dropdown for sorting isn't really needed any more.
In actual master searching on nearly everything works very well.

But at least 2 other other sorting options are really needed!
- missing: Sorting by firstname
- missing: Sorting by lastname
- (missing: Sorting by company)
- actual: Sorting by Fullname (company is set here at beginning, if exists)

If you set "Jon Doe" without company, he is found under "D" and if you set a company "Industry", he is found there under "I".
It's really problematic and like it is now, it's only usefull for business contacts with a company set.
But also for business it is weird, to find Jon Doe in "I".
Sorting for companies should be separated with headlined company names (looking like a grouping headline in contacts list). Contacts without company set should be grouped together in one group there.

Actually you don't really recognize this company categories and Fullname sorting _seems_ to look like a broken Name sorting.

**Comment by libasys** [comment]
with next version there is no more the problem you can choose on every contact show as firm or not!
is Firm selected it sorts by fullname
if not it sorts by lastname
if lastname empty sort contact by surename

**Comment by IzzySoft** [comment]
That unfortunately means I have to edit all my 250 contacts just to get the sorting fixed – and edit them again if I decide otherwise lateron. Wouldn't it be more feasible to have a click on the column headers triggering the corresponding sort (uh, OK, doesn't work for all) – or have something in the options to "override the default sorting"? True, the search box does its job – but it really looks weird (and hurts my eyes) if a list of names is sorted by lastname, but displayed by "firstname lastname". That simply seems wrong.
