### ISSUE TITLE
Empty summary of the contact 

### ISSUE THREAD

**Issue by ernesst** [libasys/contactsplus#42]
Hello, 

As accustomed with your other apps, thank you very much. 

After contact+ installation I found the summary of each my contacts in the welcome page empty, the box displays only the name of the person and under it's empty. I figured out that to fill this box, the contact information has to be ticked for each contacts. Impossible to go through all of my contact to do this action. 

I would suggest you to allow by default to display one of the mail and one of the phone number as the standard contact app is performing.  

Regards

**Comment by libasys** [comment]
the default behaviour is that only email and phone number is displayed which is prefered!

**Comment by ernesst** [comment]
I understand, however i've imported more than 100 contacts, more than 80% have only one email and one phone number, which are not displayed by default. 
I don't find efficient to go through each of them to select the email and phone number just to display them.

**Comment by deMattin** [comment]
Yes, but his suggestion was, to give a default (if importing a calendar).

But this can also have some disadvantages.
Because you don't know, which number and mail is first in exported data, it could sometimes be business mail sometimes private mail and telefone could be a rarely used number.

I thought about it a time ago, when I regonized this and I think, it isn't the worst, to be forced to go through all your contacts and set the prefered.
I have "only" 135 contacts in owncloud and some of them have more than 5 mail addresses and some more than 6 tel. numbers.

I think, it's better to see nothing but to see something, where you don't know, if it is **really** the prefered mail/tel.
And if you see something there, you are sure, you reviewed it and it's really the prefered contact.

No app is able to know, which information is relevant here and so I would suggest, to leave it as it is.

**Comment by ernesst** [comment]
I understand you point of view, it's fair and a way to force me to clean my contact.

Is this preference is also stored in android phone for the default phone number to call ?

**Comment by libasys** [comment]
please paste a vcard from your android phone here, then i can say if it or not!
