### ISSUE TITLE
Import from Contact[simple] app results in erroneous Name

### ISSUE THREAD

**Issue by farson2003** [libasys/contactsplus#44]
Steps to reproduce:
1. Create a contact in the standard Contacts app with the name "Fore Back".
2. Export addressbook..
3. Import addressbook to Contacts+

Error: The Contact "Fore Back" appears in Comtacts+ as "Back;Fore;;;" (all of which is under the last name).

**Comment by libasys** [comment]
is an export bug from contacts app, the generated vcard is buggy

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
N:Back\;Fore\;\;\;;;;;
UID:417503e4-4d78-4c77-ae8d-9132b5e10175
REV:2015-09-01T12:10:24+00:00
FN:Fore Back
END:VCARD
```

this line is buggy

```
N:Back\;Fore\;\;\;;;;;
```

correct

```
N:Back;Fore;;;
```

you can open an issue on the contacts app if you want

**Comment by libasys** [comment]
i close this issue this is not relevant for contacts+

**Comment by astroneer** [comment]
I think it's not only related to the "\;" issue.
I created Fore Back in contacts and contacts+ and did exports on both to compare the vcfs.
There is one difference in the FN field:
Contacts: FN:Fore Back
Contacts+: FN:Back Fore
If I import the contact vcf into contacts+, the displayed name is "Fore Back". Editing the contact (without changing anything, just clicking OK to re-save it) the displayed name changes to "Back Fore".

**Comment by deMattin** [comment]
If I understand it right, you have a problem with change of FN?

I think, it's a really good idea, to "repair" imported contacts, to set the Fullname the same logic on every contact in addressbook.
If you won't do this, the FN isn't really useable and may be sometimes "Jon Doe" or "Doe, Jon" or "Jon Doe Industries" or "Industries, Doe, Jon" or whatever depending on generated app ...
You see this in Outlook - here Fullnames are editable and aren't changed if you import a contact and mostly even aren't changed, if you edit the contact in Outlook (the save contact as Name).
Fullname here is completely unuseable, because every app does generate this another way - it's more an identifier with no further functionality or need to display.

**Comment by astroneer** [comment]
I agree that FN: is probably not reliable enough but it seems to me that Contacts+ is using FN: as "prime" when importing vcfs; so the displayed name can be in the wrong order (until opening the contact for editing to re-saving it; which is not nice after importing hundreds of contacts).
Probably the Contacts+ import function should use the N: field as "prime" to name the imported contacts. The N: field allows a correct separation between the first and last name.

**Comment by deMattin** [comment]
The sorting of contacts+ is in development and will be improved.
So this FN renaming won't be an issue anymore for sorting:

https://github.com/libasys/contactsplus/issues/31#issuecomment-136974120
https://github.com/libasys/contactsplus/issues/46#issuecomment-137043396

Edit:
First approach is to give the user the option, how the FN is generated ("private" with name or "business" with leading company).
But I think, other sorting options will have to be implemented sooner or later because many users need this - I'm really sure of that... ;)
(https://github.com/libasys/contactsplus/issues/34#issuecomment-137051661)
